sonar.projectKey=aws-lakehouse-mentoria-alef
sonar.projectName=aws-lakehouse-mentoria-alef
sonar.organization=julioszeferino
sonar.projectVersion=0.1.0
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**,**/*.md,infra/**
